### ISSUE TITLE
Initial design

### ISSUE THREAD

**Issue by m4v15** [InFact-coop/rsbc#14]
Hi @sgerson 

We just wanted to share with you our initial design idea/theme and get your feedback. We've made some pretty big stylistic decisions that you may or may not like, and we'll totally understand if you don't like parts of it/the general theme, any feedback would be great and hopefully help us get closer to what you might want!

As a note, the navigation bar at the top is pretty much taken from RSBC website, and we've tried to match the RSBC fonts and colours (some of the fonts are proprietary so have had to use lookalikes for now,  but hopefully they give a good idea)

![initial design - rsbc](https://user-images.githubusercontent.com/23310908/33327052-79dfdd1c-d44e-11e7-882b-382416683889.png)

**Comment by m4v15** [comment]
Also, just a note, it's better for us if you add a new comment (at the bottom) as opposed to editing the first one (just because we don't get notifications on each edit, but we do for new comments)

**Comment by sgerson** [comment]
Hi - great first start.  Let's keep the background image to UK only. 
Positioning statement - feels too much like hard work for the  SENDCOs in finding the information.  I would like to change slightly to read 'A place where you can quickly find trusted resources to support visually impaired students and their families'
I would like to add a search bar
I would like to add common questions e.g.  A VI child has just joined our school - as a quick way in - if possible.
us&you - not sure on this -let's chat about the meaning - skype me to talk through

**Comment by sgerson** [comment]
sendcommunity - I don't love it as I don't like sub brands - but happy to keep in as a point of discussion with the wider team

**Comment by sgerson** [comment]
Agreement from team - definitely don't want a sub brand SENDCOMMUNITY.  Needs to be RSBC and the positioning statement becomes a page title  e.g. Resources for SENDCOs

**Comment by astroash** [comment]
@sgerson thanks for the feedback. Apologies we weren't clear previously, the current copy is just holding text as we concentrate on working out a flow and layout of the app. We are working on the user flow right now and will be able to send you this over before the end of day.

With regards to skype, we generally have a standup every morning to discuss the working day and send updates at the end of each day. Can we send you our designs this evening, then discuss your points above, plus any others on Thursday morning before starting the last 2 days of build?

**Comment by sgerson** [comment]
ok that makes sense, thankyou.

**Comment by m4v15** [comment]
Hi @sgerson 

Sorry for delayed response, yep, like @astroash says it was all just placeholder text until we have fully worked out the copy! In terms of your other questions, I realised that without you being able to see the whole flow it would be hard for you to have any idea of where it was going or what certain things meant - I have now finished off the entire flow which you should be able to see here:

https://www.figma.com/file/gHdgDUrDJwfMP9yp6KdujqyY/RSBC-2

It still includes the name and background as before, but these can definitely be changed. Hopefully now though you can see through the whole idea of our flow as an app and we can talk on Thursday morning about things that could possibly be included/changed! Bear in mind as well that we should think of this as something to user test and the idea is to find out from the users what they like and dislike rather than a final product we (you) have to commit to right now.

**Comment by m4v15** [comment]
Also, thank you for your quick responses today! 🎉

**Comment by sgerson** [comment]
Hello both, the team have reviewed the flow and here are bullets for our standup tomorrow.  Plus I have attached examples of our sport resource.

1. Near me - should be moved to tertiary navigation not on the front screen  - front screen would be adapting environment working title, subjects replaced by curriculum and us and you is fine
2. The navigation via key stage landing page is not needed 
3. SENDCOs primary need is to understand how to adapt the environment  i.e a VI student is joining - what provisions do I need to make  - THEN how to  access the curriculum (subjects) 
4. Technology reads as how to teach IT - nomenclature should change for this
5. Resources landing page- difference between name and subject - just need to clear this up
    Add to favourites reads as though it is added to browser favourites - needs to be clearer - needs to be a benefit, bookmark resources and to do that they should easily register/ add to my profile?
6. Resources detail page - a mechanism to rate the resource and add comments/suggestions (comments not published)
7. Near me/map - we will also signpost to some RNIB resources called the sightline directory http://www.sightlinedirectory.org.uk/ as well as RSBC services
8. About you form - Change school region to local authority, add a drop down for school name (not mandatory).  KS boxes are fine.  First name, last name, work email address. Wording tweaked to say current or joining your school 
9. Option to recommend or submit a resource they recommend

Look forward to catching up tomorrow.

(Notes for me: Ensure in terms of copy tone that we aren't replacing a QTVI and ensure in comms that QTVIs endorse the information, we get them involved as a stakeholder)

(Notes for me: discussion guide - would you want to contribute content?  VI and VI and other disabilities, how would you normally find this information? 

We would let you know if new content was on the site, what other features would you come back to the RSBC for)

**Comment by sgerson** [comment]
There are 4 units for sport. 
[Physical Education and Sport for Visually Impaired - course booklet unit 2.docx](https://github.com/InFact-coop/rsbc/files/1514813/Physical.Education.and.Sport.for.Visually.Impaired.-.course.booklet.unit.2.docx)
[Physical Education and Sport for Visually Impaired - course booklet unit 1.docx](https://github.com/InFact-coop/rsbc/files/1514814/Physical.Education.and.Sport.for.Visually.Impaired.-.course.booklet.unit.1.docx)
[Physical Education and Sport for Visually Impaired - Course Booklet Unit 4 Assessment.docx](https://github.com/InFact-coop/rsbc/files/1514816/Physical.Education.and.Sport.for.Visually.Impaired.-.Course.Booklet.Unit.4.Assessment.docx)
[Physical Education and Sport for Visually Impaired - course booklet unit 3.docx](https://github.com/InFact-coop/rsbc/files/1514819/Physical.Education.and.Sport.for.Visually.Impaired.-.course.booklet.unit.3.docx)
